src_files += files('block_scan.cpp')
src_files += files('cutpoint_latency.cpp')
src_files += files('memcpy.cpp')
src_files += files('prefix_partition.cpp')
src_files += files('psa_pack.cpp')
src_files += files('psa_pack_throughput.cpp')
src_files += files('psa_pack_work.cpp')
src_files += files('psa_split.cpp')
src_files += files('psa_split2.cpp')
src_files += files('psa_splitpack.cpp')
src_files += files('psa_inline_splitpack_all.cpp')
src_files += files('psa_inline_splitpack_splitSize.cpp')
src_files += files('psa_inline_splitpack_work.cpp')
src_files += files('sample_throughput.cpp')
src_files += files('sample_throughput2.cpp')
src_files += files('scan.cpp')
src_files += files('wrs.cpp')
src_files += files('wrs_rmse.cpp')
src_files += files('wrs_rmse_sweep.cpp')
