#version 460

#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_memory_scope_semantics : enable
// #extension GL_EXT_shader_atomic_float : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_shuffle : enable
#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_EXT_control_flow_attributes : enable
#pragma use_vulkan_memory_model

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;
layout(constant_id = 0) const uint WORKGROUP_SIZE = 512;
layout(constant_id = 1) const uint SUBGROUP_SIZE = 32;
layout(constant_id = 2) const uint SPLIT_SIZE = 32;

layout(constant_id = 3) const uint THREADS_PER_SUBPROBLEM = 16;
layout(constant_id = 4) const uint LOG2_THREADS_PER_SUBPROBLEM = 4;
const uint THREADS_PER_SUBPROBLEM_MODMASK = (1 << LOG2_THREADS_PER_SUBPROBLEM) - 1;
const bool OPTIMIZE_PACK_FOR_MEMORY_COALESCING = true; // if false it's optimized for hiding the latency of memory accesses.

const uint MAX_SUBGROUP_COUNT = (WORKGROUP_SIZE + SUBGROUP_SIZE - 1) / SUBGROUP_SIZE;

const uint MAX_SUBGROUPS_PER_WORKGROUP = (WORKGROUP_SIZE + SUBGROUP_SIZE - 1) / SUBGROUP_SIZE;
const uint SUBPROBLEMS_PER_SUBGROUP = SUBGROUP_SIZE / THREADS_PER_SUBPROBLEM;
const uint MAX_SUBPROBLEMS_PER_WORKGROUP = MAX_SUBGROUPS_PER_WORKGROUP * SUBPROBLEMS_PER_SUBGROUP;

const uint THREADS_PER_SPLIT = THREADS_PER_SUBPROBLEM / 2;
const uint LOG2_THREADS_PER_SPLIT = LOG2_THREADS_PER_SUBPROBLEM - 1;

// only applicable to subgroupSplitPack
// defines how invocations within a subproblem compute splits k & k + 1
// current mask computes the split k with the first half and the second half performs k+1
const uint SUBGROUP_SPLITPACK_XOR_SHUFFLE_MASK = 1 << (LOG2_THREADS_PER_SUBPROBLEM - 1);

const bool COOPERATIVE_SPLIT = false;

#define DEBUG

struct AliasTableEntry {
    float p;
    uint a;
};

struct Split {
    uint i;
    uint j;
};

layout(set = 0, binding = 0, std430) readonly buffer in_Distribution {
    float weights[];
} g_distribution;

layout(set = 0, binding = 1, std430) readonly buffer in_PartitionIndices {
    uint heavyLight[];
} g_partitionIndices;

layout(set = 0, binding = 2, std430) readonly buffer in_PartitionPrefix {
    float heavyLight[];
} g_partitionPrefix;

layout(set = 0, binding = 3, std430) readonly buffer in_PartitionInfo {
    uint heavyCount;
} g_partitionInfo;

layout(set = 0, binding = 4, std430) readonly buffer in_DistributionInfo {
    float mean;
} g_meta;

layout(set = 0, binding = 5, std430) writeonly buffer out_AliasTable {
    AliasTableEntry table[];
} g_result;

#ifdef USE_PARTITION_ELEMENTS
layout(set = 0, binding = 6, std430) readonly buffer in_PartitionElements {
    float heavyLight[];
} g_partitionElements;
#endif

layout(push_constant) uniform PushConstant {
    uint K;
    uint N;
} pc;

Split computeSplit(uint n, float mean, uint heavyCount, uint lightCount, uint lightPrefixFirst) {
    uint a = 0;
    uint b = min(n, heavyCount);

    uint j = 0, i = 0;
    float heavy, light, sigma;

    const float target = mean * n;

    // Invariant: sigma(heavy > b) > target!
    // Invariant: sigma(heavy < a) <= target!
    while (a < b) {
        j = (a + b) / 2;
        i = min(n - j, lightCount);

        heavy = j == 0 ? 0 : g_partitionPrefix.heavyLight[j - 1];
        light = i == 0 ? 0 : g_partitionPrefix.heavyLight[lightPrefixFirst - (i - 1)];

        sigma = light + heavy;

        if (sigma >= target) {
            b = j;
        } else {
            a = j + 1;
        }
    }
    // Invariant holds after termination --> (sigma(heavy < a) <= target) --> (sigma(a-1) <= target)
    j = a - 1;
    i = min(n - j, lightCount);

    Split split;
    split.i = i;
    split.j = j;
    return split;
}
shared uvec2 workgroupShuffleScratch[MAX_SUBGROUP_COUNT];

uvec2 shuffleNextSplit(in uint k, in Split split) {
    uvec2 ij0 = uvec2(split.i, split.j);
    if (gl_SubgroupInvocationID == 0) {
        workgroupShuffleScratch[gl_SubgroupID] = ij0;
    }
    uvec2 ij1 = subgroupShuffle(ij0, gl_SubgroupInvocationID + 1);
    barrier();
    if (gl_SubgroupInvocationID == gl_SubgroupSize - 1 && gl_SubgroupID != gl_NumSubgroups - 1) {
        ij1 = workgroupShuffleScratch[gl_SubgroupID + 1];
    }
    return ij1;
}

void scalarPack(uint i0, uint i1, uint j0, uint j1, float spill,
    float averageWeight, uint lastLightIndex,
    uint lightCount, uint heavyCount, uint k) {
    uint i = i0;
    uint j = j0;

    float w = spill;
    if (k == 0) {
        uint h = g_partitionIndices.heavyLight[j];
        #ifdef USE_PARTITION_ELEMENTS
        w = g_partitionElements.heavyLight[j];
        #else
        w = g_distribution.weights[h];
        #endif
    }

    uint x = 0;
    while (i < i1 || j < j1) {
        // g_result.table[0].p = w;
        // if (x == 3) {
        //   break;
        // }
        // ++x;
        bool packHeavy;
        // Checking bounds before the numerical comparision avoids
        // Floating point inaccuracies while comparing!
        if (j >= j1) {
            // Only light buckets left.
            packHeavy = false;
        } else if (i >= i1) {
            // Only heavy buckets left.
            packHeavy = true;
        } else {
            packHeavy = w <= averageWeight;
        }

        uint h = g_partitionIndices.heavyLight[j];
        uint weightIdx;
        float weight;
        if (packHeavy) {
            weightIdx = g_partitionIndices.heavyLight[j + 1];
            #ifdef USE_PARTITION_ELEMENTS
            weight = g_partitionElements.heavyLight[j + 1];
            #else
            weight = g_distribution.weights[weightIdx];
            #endif
        } else {
            weightIdx = g_partitionIndices.heavyLight[lastLightIndex - i];
            #ifdef USE_PARTITION_ELEMENTS
            weight = g_partitionElements.heavyLight[lastLightIndex - i];
            #else
            weight = g_distribution.weights[weightIdx];
            #endif
        }

        float p;
        uint idx, a;
        if (packHeavy) {
            // Pack heavy bucket!
            p = w / averageWeight;
            a = weightIdx;
            idx = h;
            j += 1;
        } else {
            // Pack light bucket
            p = weight / averageWeight;
            a = h;
            idx = weightIdx;
            i += 1;
        }
        g_result.table[idx].p = p;
        g_result.table[idx].a = a;
        w = (w + weight) - averageWeight;
    }
}

void subgroupPackCoalesced(uint i0, uint i1, uint j0, uint j1,
    float spill,
    float averageWeight,
    uint lastLightIndex,
    uint baseInvoc,
    uint relativeSubInvoc,
    uint k
) {
    // =========== PACKING ===========

    // init Heavy
    j1 += 1;
    uint j = j0 + relativeSubInvoc;
    uint jx = 0;
    int remainingHeavy = int(j1 - j0);
    uint h2;
    float hw;
    AliasTableEntry he;
    if (j < j1) {
        h2 = g_partitionIndices.heavyLight[j];
        #ifdef USE_PARTITION_ELEMENTS
        hw = g_partitionIndices.heavyLight[j];
        #else
        hw = g_distribution.weights[h2];
        #endif
    }

    // init light
    uint i = i0 + relativeSubInvoc;
    uint ix = 0;
    int remainingLight = int(i1 - i0);
    uint l2;
    float lw = 0;
    AliasTableEntry le;
    if (i < i1) {
        l2 = g_partitionIndices.heavyLight[lastLightIndex - i];
        #ifdef USE_PARTITION_ELEMENTS
        lw = g_partitionIndices.heavyLight[lastLightIndex - i];
        #else
        lw = g_distribution.weights[l2];
        // lw = 0;
        #endif
    }

    float w = spill;
    uint h;
    if (k == 0) {
        uvec2 temp = subgroupBroadcast(uvec2(h2, floatBitsToUint(hw)), baseInvoc + jx);
        h = temp.x;
        w = uintBitsToFloat(temp.y);
    } else {
        h = subgroupBroadcast(h2, baseInvoc + jx);
    }
    jx += 1;
    remainingHeavy -= 1;

    bool hasLight = remainingLight > 0;
    bool hasHeavy = remainingHeavy > 0;
    bool packHeavy;

    while (hasLight || hasHeavy) {
        // Checking bounds before the numerical comparision avoids
        // Floating point inaccuracies while comparing!
        if (!hasHeavy) {
            packHeavy = false;
        } else if (!hasLight) {
            packHeavy = true;
        } else {
            packHeavy = (w <= averageWeight);
        }
        uint weightIdx;
        float weight;
        uvec2 v;
        uint owner;
        if (packHeavy) {
            v = uvec2(h2, floatBitsToUint(hw));
            owner = jx++;
            remainingHeavy--;
        } else {
            v = uvec2(l2, floatBitsToUint(lw));
            owner = ix++;
            remainingLight--;
        }
        v = subgroupBroadcast(v, baseInvoc + owner);

        if (packHeavy) {
            // Pack heavy bucket!
            if (relativeSubInvoc == jx - 2) {
                he.a = v.x;
                he.p = w / averageWeight;
            }

            h = v.x;
        } else {
            // Pack light bucket
            if (relativeSubInvoc == ix - 1) {
                le.p = uintBitsToFloat(v.y) / averageWeight;
                le.a = h;
            }
        }

        if (owner == (THREADS_PER_SUBPROBLEM - 1)) {
            if (packHeavy) {
                if (relativeSubInvoc < (THREADS_PER_SUBPROBLEM - 1)) {
                    g_result.table[h2] = he;
                }
                j += THREADS_PER_SUBPROBLEM - 1;
                jx = 1;
                if (j < j1) {
                    h2 = g_partitionIndices.heavyLight[j];
                    #ifdef USE_PARTITION_ELEMENTS
                    hw = g_partitionIndices.heavyLight[j];
                    #else
                    hw = g_distribution.weights[h2];
                    #endif
                }
            } else {
                if (relativeSubInvoc < (THREADS_PER_SUBPROBLEM)) {
                    g_result.table[l2] = le;
                }
                i += THREADS_PER_SUBPROBLEM;
                ix = 0;
                if (i < i1) {
                    l2 = g_partitionIndices.heavyLight[lastLightIndex - i];
                    #ifdef USE_PARTITION_ELEMENTS
                    lw = g_partitionIndices.heavyLight[lastLightIndex - i];
                    #else
                    lw = g_distribution.weights[l2];
                    // lw = 0;
                    #endif
                }
            }
        }

        hasLight = remainingLight > 0;
        hasHeavy = remainingHeavy > 0;
        w += uintBitsToFloat(v.y) - averageWeight;
    }
    if (relativeSubInvoc < ix) {
        g_result.table[l2] = le;
    }

    if (relativeSubInvoc < jx - 1) {
        g_result.table[h2] = he;
    }
    // if (j1 == heavyCount) {
    //     // Last heavy element overal has to be handled seperately otherwise,
    //     // we access heavyIndices out of bound.
    //     // Maybe this would actually be fine because of our layout. Then the residual of the
    //     // last element which should always be zero, but numerical instabilities would be
    //     // reassigned to the last light element, both are probably fine, but here we choose to
    //     // redirect to not have the last heavy element redirect to anything makes it easier to debug!
    //     g_result.table[h].p = 1.0f;
    //     g_result.table[h].a = h;
    // }
}

void subgroupPackCyclicBuffer(
    uint i0,
    uint i1,
    uint j0,
    uint j1,
    float spill,
    float averageWeight,
    uint lastLightIndex,
    uint baseInvoc,
    uint relativeSubInvoc,
    uint k
) {
    // We can think about relativeSubInvoc as a replacement for the gl_SubgroupInvocationID
    // Specifically baseInvoc + relativeSubInvoc == gl_SubgroupInvocationID.
    // Only invocations with the same baseInvoc will communicate!
    uint i = i0 + relativeSubInvoc;
    uint j = j0 + relativeSubInvoc;
    // =========== PACKING ===========

    float shfl_lightWeight;
    float shfl_heavyWeight;
    uint shfl_lightIndex;
    uint shfl_heavyIndex;
    AliasTableEntry shfl_writebackHeavy;
    AliasTableEntry shfl_writebackLight;

    // ========= INIT-SHFL-REG-BUFFERS ==========
    // Init light
    if (i < i1) {
        shfl_lightIndex = g_partitionIndices.heavyLight[lastLightIndex - i];
        // bad dependency -> Stall Long Scoreboard!
        shfl_lightWeight = g_distribution.weights[shfl_lightIndex];
    }
    #ifdef DEBUG
    else {
        shfl_lightIndex = -1;
    }
    #endif

    // Init heavy
    if (j <= j1) { // we are only interessted in the index of j1
        shfl_heavyIndex = g_partitionIndices.heavyLight[j];
    }
    #ifdef DEBUG
    else {
        shfl_heavyIndex = -1;
    }
    #endif
    if (j <= j1) { // not the weight at j1
        if (relativeSubInvoc == 0 && k != 0) {
            shfl_heavyWeight = spill;
        } else {
            shfl_heavyWeight = g_distribution.weights[shfl_heavyIndex];
        }
    }

    // shfl_*Owner is the relativeSubInvoc of the
    // invocation which owns the next light / next heavy index / element.
    // Specials case: if shfl_heavyOwner == THREADS_PER_SUBPROBLEM
    // we don't have any heavy elements left.
    uint shfl_lightOwner = 0;
    uint shfl_heavyOwner = 0;

    // not strictly identical to the split size as not all
    // input sizes are divisible by it!
    uint lightRemaining = (i1 - i0);
    uint heavyRemaining = (j1 - j0);
    uint x = 0;
    while (lightRemaining != 0 || heavyRemaining != 0) {
        bool packHeavy;
        // Invocation, which owns the current heavy weight decides
        // if we pack heavy of light based on the current heavy weight.
        if (relativeSubInvoc == shfl_heavyOwner) {
            packHeavy = (shfl_heavyWeight <= averageWeight);
            if (lightRemaining == 0) {
                packHeavy = true;
            }
            if (heavyRemaining == 0) {
                packHeavy = false;
            }
        }

        packHeavy = subgroupShuffle(packHeavy, baseInvoc + shfl_heavyOwner);

        if (packHeavy) {
            uint nextHeavyOwner = (shfl_heavyOwner + 1) & THREADS_PER_SUBPROBLEM_MODMASK;
            if (relativeSubInvoc == shfl_heavyOwner
                    || relativeSubInvoc == nextHeavyOwner) {
                uint currentHeavyIndex = subgroupShuffle(shfl_heavyIndex, baseInvoc + shfl_heavyOwner);
                float currentHeavyWeight = subgroupShuffle(shfl_heavyWeight, baseInvoc + shfl_heavyOwner);
                if (relativeSubInvoc == nextHeavyOwner) {
                    shfl_writebackHeavy.p = currentHeavyWeight / averageWeight;
                    shfl_writebackHeavy.a = shfl_heavyIndex;
                    // NOTE: writeback, buffering may improve performance on AMD or intel, but not tested.
                    g_result.table[currentHeavyIndex] = shfl_writebackHeavy;
                    // g_result.table[currentHeavyIndex].p = currentHeavyWeight / averageWeight;
                    // g_result.table[currentHeavyIndex].a = shfl_heavyIndex;
                    shfl_heavyWeight = (shfl_heavyWeight - averageWeight) + currentHeavyWeight;
                }
                if (relativeSubInvoc == shfl_heavyOwner) {
                    j += THREADS_PER_SUBPROBLEM;
                    if (j <= j1) {
                        // for the very last heavy element this overflows into the light array, which is actually fine,
                        // as the last heavy element should theoretically not redirect at all
                        // However due to numerical instability it very well might and in our implementation
                        // we just overflow into the last light element, which then might be oversampled
                        shfl_heavyIndex = g_partitionIndices.heavyLight[j];
                        shfl_heavyWeight = g_distribution.weights[shfl_heavyIndex];
                    }
                }
            }
            shfl_heavyOwner = nextHeavyOwner;
            --heavyRemaining;
        } else {
            if (relativeSubInvoc == shfl_heavyOwner ||
                    relativeSubInvoc == shfl_lightOwner) {
                uint currentLightIndex = subgroupShuffle(shfl_lightIndex, baseInvoc + shfl_lightOwner);
                float currentLightWeight = subgroupShuffle(shfl_lightWeight, baseInvoc + shfl_lightOwner);
                if (relativeSubInvoc == shfl_heavyOwner) {
                    shfl_writebackLight.p = currentLightWeight / averageWeight;
                    shfl_writebackLight.a = shfl_heavyIndex;
                    // NOTE: writeback, buffering may improve performance on AMD or intel, but not tested.
                    g_result.table[currentLightIndex] = shfl_writebackLight; 
                    // g_result.table[currentLightIndex].p = currentLightWeight / averageWeight;
                    // g_result.table[currentLightIndex].a = shfl_heavyIndex;
                    shfl_heavyWeight = (shfl_heavyWeight - averageWeight) + currentLightWeight;
                }
                if (relativeSubInvoc == shfl_lightOwner) {
                    i += THREADS_PER_SUBPROBLEM;
                    if (i < i1) {
                        shfl_lightIndex = g_partitionIndices.heavyLight[lastLightIndex - i];
                        shfl_lightWeight = g_distribution.weights[shfl_lightIndex];
                    }
                }
            }

            shfl_lightOwner = (shfl_lightOwner + 1) & THREADS_PER_SUBPROBLEM_MODMASK;
            --lightRemaining;
        }
    }
}

uint SubgroupClusteredBallotBitCountForSplitCoop(bool
    value,
    uint
    clusterBase) {
    uvec4 ballot = subgroupBallot(value);
    uint count = 0;
    count += bitCount(ballot.x
                & (((1 << THREADS_PER_SPLIT) - 1) << clusterBase
                )
        );
    if (SUBGROUP_SIZE > 32) {
        // NOTE: THIS PROBABLY DOES NOT WORK!!! IT'S NOT TESTED I DONT HAVE THE HARDWARE!!!!!
        count += bitCount(ballot.y
                    & (((1 << THREADS_PER_SPLIT) - 1) << (clusterBase % 32)
                    )
            );
    }

    return count;
}

// Uncompetitive and uselessly complicated.
Split computeSplitCoop(uint n, float mean, uint heavyCount, uint lightCount, uint lightPrefixFirst,
    uint baseInvoc, uint relativeSubInvoc) {
    // Implement cooperative binary search with THREADS_PER_SUBPROBLEM invocations within.
    // baseInvoc is the first gl_SubgroupInvocationID, which is participating
    // relativeSubInvoc is the index of the invocation which is participating between 0 and THREADS_PER_SUBPROBLEM - 1
    uint a = 0;
    uint b = heavyCount - 1;
    float heavy, light, sigma;
    uint j = 0, i = 0;

    const float target = mean * n;
    uint range = b - a;
    while (range < THREADS_PER_SPLIT) {
        j = a + (range * (relativeSubInvoc + 1)) / (THREADS_PER_SPLIT + 1);

        // j = (a + b) / 2;
        i = min(n - j, lightCount - 1);

        heavy = j == 0 ? 0 : g_partitionPrefix.heavyLight[j - 1];
        light = i == 0 ? 0 : g_partitionPrefix.heavyLight[lightPrefixFirst - i + 1];

        sigma = light + heavy;

        // uvec4 ballot = subgroupBallot(sigma <= target);

        uint amountOfInvocWhichAreLower = SubgroupClusteredBallotBitCountForSplitCoop(sigma <= target, baseInvoc);

        //

        if (amountOfInvocWhichAreLower == 0) {
            b = subgroupShuffle(j - 1, baseInvoc);
        } else if (amountOfInvocWhichAreLower == THREADS_PER_SPLIT) {
            a = subgroupShuffle(j, baseInvoc + THREADS_PER_SPLIT - 1);
        }
        else {
            a = subgroupShuffle(j, baseInvoc + amountOfInvocWhichAreLower - 1);
            b = subgroupShuffle(j - 1, baseInvoc + amountOfInvocWhichAreLower);
        }

        range = b - a;
        // break;
    }

    while (a <= b) {
        j = (a + b) / 2;
        i = min(n - j, lightCount - 1);

        heavy = j == 0 ? 0 : g_partitionPrefix.heavyLight[j - 1];
        light = i == 0 ? 0 : g_partitionPrefix.heavyLight[lightPrefixFirst - i + 1];

        sigma = light + heavy;

        if (sigma <= target) {
            a = j + 1;
        } else {
            b = j - 1;
        }
    }
    j = b; //lower bound still
    i = min(n - j, lightCount - 1);
    Split split;
    split.i = i;
    split.j = j;
    return split;
}

void subgroupSplitPack() {
    // ASSERT THREADS_PER_PACK >= 2
    const uint K = pc.K;

    uint subproblemID = gl_SubgroupInvocationID / THREADS_PER_SUBPROBLEM; // subproblemID within a subgroup!
    // k is the global id of the subproblem
    uint k = subproblemID + gl_SubgroupID * SUBPROBLEMS_PER_SUBGROUP
            + gl_WorkGroupID.x * MAX_SUBPROBLEMS_PER_WORKGROUP;

    if (k >= K) {
        return;
    }

    // fetching some globals
    const float mean = g_meta.mean;
    const uint N = pc.N;
    const uint heavyCount = g_partitionInfo.heavyCount;
    const uint lightCount = N - heavyCount;
    const uint lastLightIndex = N - 1;

    // first invocation within a subproblem
    const uint baseInvoc = (gl_SubgroupInvocationID / THREADS_PER_SUBPROBLEM) * THREADS_PER_SUBPROBLEM;
    // replaces gl_SubgroupInvocationID
    const uint relativeSubInvoc = gl_SubgroupInvocationID - baseInvoc;

    uint shuffleK = k;
    uint splitBaseInvoc = baseInvoc;
    uint splitRelativeSubInvoc = relativeSubInvoc;

    // odd invocation compute split k, even invocations compute split k+1
    if ((relativeSubInvoc & SUBGROUP_SPLITPACK_XOR_SHUFFLE_MASK) != 0) {
        shuffleK += 1;
        splitBaseInvoc ^= SUBGROUP_SPLITPACK_XOR_SHUFFLE_MASK;
        splitRelativeSubInvoc ^= SUBGROUP_SPLITPACK_XOR_SHUFFLE_MASK;
    }
    uint n = shuffleK * SPLIT_SIZE;

    Split s0;
    if (shuffleK == 0) {
        s0.i = 0;
        s0.j = 0;
    } else if (shuffleK == K) {
        s0.i = lightCount;
        s0.j = heavyCount;
    } else {
        if (COOPERATIVE_SPLIT) {
            s0 = computeSplitCoop(n, mean, heavyCount, lightCount, lastLightIndex, splitBaseInvoc, splitRelativeSubInvoc);
        } else {
            s0 = computeSplit(n, mean, heavyCount, lightCount, lastLightIndex);
        }
    }

    // shuffle splits between xor related invocations
    uvec2 s0Repr = uvec2(s0.i, s0.j);
    uvec2 s1Repr = subgroupShuffleXor(s0Repr, SUBGROUP_SPLITPACK_XOR_SHUFFLE_MASK);

    if ((relativeSubInvoc & SUBGROUP_SPLITPACK_XOR_SHUFFLE_MASK) != 0) {
        s0.i = s1Repr.x;
        s0.j = s1Repr.y;
        s1Repr.xy = s0Repr.xy;
    }

    float spill = 0;

    if (OPTIMIZE_PACK_FOR_MEMORY_COALESCING) {
        subgroupPackCoalesced(
            s0.i,
            s1Repr.x,
            s0.j,
            s1Repr.y,
            spill,
            mean,
            lastLightIndex,
            baseInvoc,
            relativeSubInvoc,
            k
        );
    } else {
        subgroupPackCyclicBuffer(
            s0.i,
            s1Repr.x,
            s0.j,
            s1Repr.y,
            spill,
            mean,
            lastLightIndex,
            baseInvoc,
            relativeSubInvoc,
            k
        );
    }
}

void scalarSplitPackEdge(uint i0, uint i1, uint j0, uint j1, float spill,
    float averageWeight, uint lastLightIndex,
    uint lightCount, uint heavyCount) {
    uint i = i0;
    uint j = j0;

    float w = spill;
    if (w == 0.0f) {
        uint h = g_partitionIndices.heavyLight[j];
        w = g_partitionPrefix.heavyLight[j] - g_partitionPrefix.heavyLight[j - 1];
    }

    bool packHeavy = w <= averageWeight;

    uint h = g_partitionIndices.heavyLight[j];

    uint weightIdx;
    float weight;
    if (packHeavy) {
        uint hx = j + 1;
        weightIdx = g_partitionIndices.heavyLight[hx];
    } else {
        uint lx = lastLightIndex - i;
        weightIdx = g_partitionIndices.heavyLight[lastLightIndex - i];
        weight = g_partitionPrefix.heavyLight[lx] - g_partitionPrefix.heavyLight[lx + 1];
    }
    float p;
    uint idx, a;
    if (packHeavy) {
        // Pack heavy bucket!
        p = w / averageWeight;
        a = weightIdx;
        idx = h;
    } else {
        // Pack light bucket
        p = weight / averageWeight;
        a = h;
        idx = weightIdx;
    }

    g_result.table[idx].p = p;
    g_result.table[idx].a = a;
}

void scalarSplitPack() {
    const uint N = pc.N;
    const uint K = pc.K;
    const float mean = g_meta.mean;
    const uint heavyCount = g_partitionInfo.heavyCount;
    const uint lightCount = N - heavyCount;
    const uint lightPrefixFirst = N - 1;

    uint k = gl_WorkGroupID.x * (WORKGROUP_SIZE - 1) + gl_LocalInvocationID.x;

    if (k > K) {
        return; // Ensure k does not exceed or equal the number of splits (K)
    }

    uint n = k * SPLIT_SIZE;

    // const uint n = ceilMulDiv(N, k, K);

    Split split;
    if (k == 0) {
        split.i = 0;
        split.j = 0;
    } else if (k == K) {
        split.i = lightCount;
        split.j = heavyCount;
    } else {
        split = computeSplit(n, mean, heavyCount, lightCount, lightPrefixFirst);
    }

    // NOTE (1): there was a idea here: 
    // We tried to fix the nonmonotone sequence of i and j with subgroupInclusiveMax
    // and this also kind of does what it should however we do not find that it 
    // really improves the numerical stability. The only 
    // option that really seems sensible is to use block-wise scans instead of 
    // a large prefix sum over the heavy / light elements to avoid the 
    // floating-point cancelation. 2 floats better than 1 float =^).
    // split.i = subgroupInclusiveMax(split.i);
    // split.j = subgroupInclusiveMax(split.j);

    uvec2 ij1 = shuffleNextSplit(k, split);

    if (k == K) {
        return;
    }

    if (gl_LocalInvocationID.x == gl_WorkGroupSize.x - 1) {
        return;
    }
    // NOTE : see NOTE (1):
    // uint i0 = subgroupInclusiveMax(split.i);
    // uint j0 = subgroupInclusiveMax(split.j);
    // uint i1 = subgroupInclusiveMax(ij1.x);
    // uint j1 = subgroupInclusiveMax(ij1.y);
    // uint i0 = min(split.i, ij1.x);
    // uint j0 = min(split.j, ij1.y);
    // uint i1 = max(ij1.x, split.i);
    // uint j1 = max(ij1.y, split.j);

    uint i0 = split.i;
    uint j0 = split.j;
    uint i1 = ij1.x;
    uint j1 = ij1.y;

    float light = i0 == 0 ? 0 : g_partitionPrefix.heavyLight[lightPrefixFirst - (i0 - 1)];
    float heavy2 = g_partitionPrefix.heavyLight[j0]; // weight of j+1 elements (inclusive prefix) and j represents a count!
    float sigma2 = heavy2 + light;
    float target = (i0 + j0) * mean;

    float spill = sigma2 - target;

    scalarPack(i0, i1, j0, j1, spill, mean, lightPrefixFirst, lightCount, heavyCount, k);
}

void main(void)
{
    if /* constexpr */ (THREADS_PER_SUBPROBLEM == 1) {
        scalarSplitPack();
    } else {
        subgroupSplitPack();
    }
}
